import type { Category } from '@/types'

export const defaultCategories: Category[] = [
  // Expenses
  {
    id: 'food-grocery',
    name: 'Alimentation & Courses',
    icon: 'ShoppingCart',
    color: '#22c55e',
    isIncome: false,
    isExcludedFromStats: false,
    order: 1,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'food-restaurant',
    name: 'Restaurants',
    icon: 'Utensils',
    color: '#f97316',
    isIncome: false,
    isExcludedFromStats: false,
    order: 2,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'transport',
    name: 'Transport',
    icon: 'Car',
    color: '#3b82f6',
    isIncome: false,
    isExcludedFromStats: false,
    order: 3,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'entertainment',
    name: 'Loisirs',
    icon: 'Film',
    color: '#a855f7',
    isIncome: false,
    isExcludedFromStats: false,
    order: 4,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'abonnements',
    name: 'Abonnements',
    icon: 'Repeat',
    color: '#f472b6',
    isIncome: false,
    isExcludedFromStats: false,
    order: 5,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'amazon',
    name: 'Amazon',
    icon: 'Package',
    color: '#ff9900',
    isIncome: false,
    isExcludedFromStats: false,
    order: 5,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: 'ShoppingBag',
    color: '#ec4899',
    isIncome: false,
    isExcludedFromStats: false,
    order: 6,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'loyer',
    name: 'Loyer',
    icon: 'Home',
    color: '#eab308',
    isIncome: false,
    isExcludedFromStats: false,
    order: 6,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'energie',
    name: 'Énergie',
    icon: 'Zap',
    color: '#f59e0b',
    isIncome: false,
    isExcludedFromStats: false,
    order: 7,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'telecom',
    name: 'Telecom',
    icon: 'Smartphone',
    color: '#14b8a6',
    isIncome: false,
    isExcludedFromStats: false,
    order: 7,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'health',
    name: 'Sante',
    icon: 'Heart',
    color: '#ef4444',
    isIncome: false,
    isExcludedFromStats: false,
    order: 8,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bank-fees',
    name: 'Banque & Frais',
    icon: 'Building',
    color: '#6b7280',
    isIncome: false,
    isExcludedFromStats: false,
    order: 9,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Income
  {
    id: 'salary',
    name: 'Salaire',
    icon: 'Banknote',
    color: '#10b981',
    isIncome: true,
    isExcludedFromStats: false,
    order: 10,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'transfer-in',
    name: 'Virements recus',
    icon: 'ArrowDownLeft',
    color: '#22d3ee',
    isIncome: true,
    isExcludedFromStats: false,
    order: 11,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'caf',
    name: 'CAF',
    icon: 'Baby',
    color: '#06b6d4',
    isIncome: true,
    isExcludedFromStats: false,
    order: 12,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'refund',
    name: 'Remboursements',
    icon: 'RotateCcw',
    color: '#84cc16',
    isIncome: true,
    isExcludedFromStats: false,
    order: 12,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Transfers (excluded from stats)
  {
    id: 'compte-a-compte',
    name: 'Compte a compte',
    icon: 'ArrowLeftRight',
    color: '#8b5cf6',
    isIncome: true,
    isExcludedFromStats: false,
    order: 13,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'transfer-out',
    name: 'Virements emis',
    icon: 'ArrowUpRight',
    color: '#f43f5e',
    isIncome: false,
    isExcludedFromStats: true,
    order: 14,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'internal',
    name: 'Prelevements',
    icon: 'Repeat',
    color: '#8b5cf6',
    isIncome: false,
    isExcludedFromStats: false, // Changed: include in stats (most PRLV are real expenses)
    order: 14,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },

  // Other
  {
    id: 'other',
    name: 'Autres',
    icon: 'MoreHorizontal',
    color: '#94a3b8',
    isIncome: false,
    isExcludedFromStats: false,
    order: 99,
    isDefault: true,
    createdAt: new Date().toISOString(),
  },
]
